# Generated by Django 5.2.6 on 2025-09-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, default='https://anxkatxbafgpahipxzsw.supabase.co/storage/v1/object/public/avatar/default.png', null=True),
        ),
    ]
