# Generated by Django 5.2.6 on 2025-09-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default.png",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
