# Generated by Django 5.2.6 on 2025-09-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='buy_count',
            field=models.PositiveIntegerField(default=0, help_text='Amount of tickets sold for this movie'),
        ),
    ]
