# Generated by Django 5.2.6 on 2025-09-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_buy_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ticket_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Price for watching at the cinema', max_digits=7),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movies/posters/'),
        ),
    ]
