# Generated by Django 5.2.6 on 2025-09-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movie_ticket_price_alter_movie_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinema",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
