# Generated by Django 5.2.6 on 2025-09-25 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_poster'),
        ('movies', '0004_cinema_phone_number'),
    ]

    operations = [
    ]
