# Generated by Django 5.2.6 on 2025-09-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_ticket_unique_together_remove_ticket_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='quantity',
        ),
        migrations.AddField(
            model_name='booking',
            name='seats_booked',
            field=models.JSONField(default=list, help_text='Ticket quantity'),
        ),
    ]
