# Generated by Django 5.2.6 on 2025-09-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_quantity_booking_seats_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.CharField(default='', max_length=200),
        ),
    ]
